---
root: true

parserOptions:
    ecmaVersion: 6

env:
    node: true
    es6: true

globals:
    Intl: false

extends: 'eslint:recommended'

rules:
    # We allow unused args
    no-unused-vars: [2, {"args": "after-used"}]

    no-unexpected-multiline: 2
    valid-jsdoc: [2, {"prefer": {"return": "returns", "arg": "param", "class": "constructor"}}]

    consistent-return: 2
    curly: [2, "all"]
    default-case: 2
    dot-location: [2, "property"]
    dot-notation: 2
    eqeqeq: 2
    guard-for-in: 2
    no-alert: 2
    no-caller: 2
    no-else-return: 2
    no-eval: 2
    no-extra-bind: 2
    no-implied-eval: 2
    no-floating-decimal: 2
    no-iterator: 2
    no-labels: 2
    no-lone-blocks: 2
    no-loop-func: 2
    no-multi-spaces: 2
    no-multi-str: 2
    no-native-reassign: 2
    no-new-func: 2
    no-new-wrappers: 2
    no-new: 2
    no-octal-escape: 2
    no-proto: 2
    no-return-assign: 2
    no-script-url: 2
    no-self-compare: 2
    no-sequences: 2
    no-throw-literal: 2
    no-unused-expressions: 2
    no-useless-call: 2
    no-useless-concat: 2
    no-void: 2
    no-with: 2
    radix: 2
    wrap-iife: 2
    yoda: [2, "never"]

    strict: [2, "global"]

    no-catch-shadow: 2
    no-label-var: 2
    no-shadow-restricted-names: 2
    no-shadow: 2
    no-use-before-define: 2

    callback-return: 2
    global-require: 2
    handle-callback-err: [2, "^(err|error)$"]
    no-mixed-requires: 2
    no-new-require: 2
    no-path-concat: 2
    no-process-exit: 2
    no-sync: 2

    brace-style: [2, "1tbs", {"allowSingleLine": true}]
    comma-style: [2, "last"]
    consistent-this: [2, "self"]
    eol-last: 2
    func-style: [2, "declaration", {"allowArrowFunctions": true}]
    indent: [2, "tab"]
    key-spacing: 2
    keyword-spacing: [2, {"before": true, "after": true}]
    linebreak-style: [2, "unix"]
    new-cap: 2
    new-parens: 2
    no-array-constructor: 2
    no-lonely-if: 2
    no-multiple-empty-lines: 2
    no-nested-ternary: 2
    no-new-object: 2
    no-spaced-func: 2
    no-trailing-spaces: 2
    no-unneeded-ternary: 2
    quote-props: [2, "as-needed"]
    quotes: [2, "single", "avoid-escape"]
    require-jsdoc: [2, {"require": {"FunctionDeclaration": true, "MethodDefinition": true}}]
    semi: [2, "always"]
    space-before-blocks: 2
    space-before-function-paren: [2, "never"]
    space-infix-ops: 2
    space-unary-ops: [2, {"words": true, "nonwords": false}]
    spaced-comment: [2, "always"]

    arrow-body-style: [2, "as-needed"]
    arrow-parens: [2, "as-needed"]
    arrow-spacing: 2
    generator-star-spacing: [2, {"before": false, "after": true}]
    no-confusing-arrow: [2, {"allowParens": true}]
    no-const-assign: 2
    require-yield: 2

    array-callback-return: 2
    no-implicit-globals: 2
    no-new-symbol: 2
    no-self-assign: 2
    no-unmodified-loop-condition: 2
    no-useless-constructor: 2
    no-whitespace-before-property: 2
    one-var-declaration-per-line: 2
    # @TODO(mwiller) 2016-03-14: Turn this on when we're on a version of Node that supports rest params
    #prefer-rest-params: 2
    template-curly-spacing: 2
    yield-star-spacing: [2, "after"]
    no-useless-escape: 2
    max-statements-per-line: [2, {"max": 1}]
