name: Integration tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node: ['16', '18', '20']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run integration tests
        run: npm run jest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JWT_CONFIG: ${{ secrets.JWT_CONFIG }}
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
